# ----------------- default.yaml – Iberia 0.25° -----------------
paths:
  raw_dir:        data/raw
  hres_dir:       data/raw/hres                  # NetCDF IFS-HRES
  interim_dir:    data/interim
  processed_dir:  data/processed
  models:         models
  outputs:        outputs
  feature_table:  data/processed/features.parquet
  best_model_dir: models/xgb_optuna_202507120738

data:
  start_date: "2018-01-01T00:00:00Z"
  end_date:   "2025-06-30T23:00:00Z"

  split_dates:
    train_end: "2023-12-31T23:00:00Z"
    val_end:   "2024-12-31T23:00:00Z"      # todo 2024 = validación

# --- Localización media peninsular (≈ Talavera de la Reina) ---
site:
  lat: 40.0
  lon: -4.0

# ---------- IDs ESIOS ----------
ids_esios:
  wind:      551
  solar_pv:  10206
  demand:    1293

# ---------- ERA5 variables (opcional) ----------
variables:
  era5:
    # Todos los registros llevan product_type=reanalysis - necesario para ERA5
    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: surface_solar_radiation_downwards,              short_name: ssrd,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: total_sky_direct_solar_radiation_at_surface,    short_name: fdir,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: surface_solar_radiation_downwards_clear_sky,    short_name: ssrdc,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - { dataset: reanalysis-era5-single-levels, product_type: reanalysis,
        name: 2m_temperature,                                 short_name: 2t,
        area: [ 46,-10,27,4 ], grid: [ 0.25,0.25 ], data_format: netcdf }

    - { dataset: reanalysis-era5-single-levels, product_type: reanalysis,
        name: 2m_dewpoint_temperature,                        short_name: 2d,
        area: [ 46,-10,27,4 ], grid: [ 0.25,0.25 ], data_format: netcdf }

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: surface_pressure,                               short_name: sp,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: 10m_u_component_of_wind,                        short_name: 10u,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: 10m_v_component_of_wind,                        short_name: 10v,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    #- {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
    #   name: 100m_u_component_of_wind,                       short_name: 100u,
    #   area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    #- {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
    #   name: 100m_v_component_of_wind,                       short_name: 100v,
    #   area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: total_cloud_cover,                              short_name: tcc,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: total_precipitation,                            short_name: tp,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}

    - {dataset: reanalysis-era5-single-levels, product_type: reanalysis,
       name: convective_available_potential_energy,          short_name: cape,
       area: [46,-10,27,4], grid: [0.25,0.25], data_format: netcdf}


feature_engineering:
  # CAMBIO: más columnas sujetas a retardos/medias
  lag_roll_cols: ["t2m", "d2m", "wind_speed10", "wind_speed100", "ssrd_ghi", "fdir", "fdif", "log_wind_speed"]
  lags:          [1, 96]      # 15 min y diel (96×15 min = 24 h)
  rolling_means: [4]          # 1 h suavizado (4×15 min)

# --- evolución de capacidad instalada (MW) ---
capacity_timeline:
  wind:
    2018-01-01: 23000
    2019-07-01: 25000
    2020-01-01: 27000
    2021-01-01: 29000
    2022-01-01: 30500
    2023-01-01: 31500
    2024-01-01: 32007
  solar_pv:
    2018-01-01: 5000
    2019-01-01: 7000
    2020-01-01: 9000
    2021-01-01: 14000
    2022-01-01: 22000
    2023-01-01: 29000
    2024-01-01: 32043


# ---------- Optuna ----------
optuna:
  n_trials: 60

# ---------- Modelo ----------
model:
  targets: ["wind", "solar_pv"]



