paths:
  raw_dir: data/raw
  interim_dir: data/interim
  processed_dir: data/processed
  models: models
  feature_table: data/processed/features.parquet

data:
  start_date: "2024-01-01T00:00:00Z"
  end_date:   "2025-06-24T23:00:00Z"


variables:
  era5:
    - dataset: reanalysis-era5-single-levels     # ← donde vive el GHI
      name: ghi
      short_name: surface_solar_radiation_downwards

    - dataset: reanalysis-era5-land              # t2m sí está en ERA5-Land
      name: t2m
      short_name: 2m_temperature

    - dataset: reanalysis-era5-land              # u10 también
      name: u10
      short_name: 10m_u_component_of_wind



feature_engineering:
  lags: [1, 2, 3, 6, 12, 24, 48]
  rolling_means: [3, 6]

optuna:
  n_trials: 50
